e2e Record Splitter test scenarios
sawantpritam/record-splitter-transform pull request #1
Opened 2022-06-16 04:41 UTC by itsmekumari

@sawantpritam Please review

2022-06-16 07:21 UTC, sawantpritam requested changes

2022-06-16 07:21 UTC, sawantpritam commented on pom.xml
> +      <!--<exclusions>
Remove commented exclusions

2022-06-16 07:21 UTC, sawantpritam commented on src/e2e-test/resources/pluginParameters.properties
> +## FILE-PLUGIN-PROPERTIES-START
Remove unused file properties

2022-06-16 07:21 UTC, sawantpritam commented on src/e2e-test/resources/testdata/file/CSV_DATATYPE_TEST_1.csv
> +id,name,yearofbirth,isdeleted,email,createddate,revenue,points,longdatatype,doubledatatype,date,null,BytesData
Remove unused testdata files

2022-06-16 07:21 UTC, sawantpritam commented on src/e2e-test/resources/cmek-config.properties
> +cmekGCS=projects/cdf-athena/locations/us/keyRings/gcs-cmek-test/cryptoKeys/test_key
Remove this file as we dont have cmek test scenarios

2022-06-16 07:21 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/utils/E2ETestConstants.java
> +}
Empty constants file can be removed.

2022-06-16 07:21 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/recordsplitter/actions/RecordSplitterActions.java
> +  private static final Logger logger = LoggerFactory.getLogger(RecordSplitterActions.class);
Remove unused logger

2022-06-16 07:21 UTC, sawantpritam commented on src/e2e-test/features/recordsplitter/BigQueryToRecordSplitter.feature
> +  Scenario: To verify data is getting transferred from BigQuery to BigQuery sink plugin successfully with Delimiter
with Delimiter -> with record splitter

check all descriptions

2022-06-16 07:22 UTC, sawantpritam commented
Add Override service account details steps in all scenarios

2022-06-16 13:46 UTC, itsmekumari commented on pom.xml
> +      <!--<exclusions>
Removed.

2022-06-16 13:46 UTC, itsmekumari commented on src/e2e-test/resources/testdata/file/CSV_DATATYPE_TEST_1.csv
> +id,name,yearofbirth,isdeleted,email,createddate,revenue,points,longdatatype,doubledatatype,date,null,BytesData
Removed.

2022-06-16 13:46 UTC, itsmekumari commented on src/e2e-test/resources/pluginParameters.properties
> +## FILE-PLUGIN-PROPERTIES-START
Removed.

2022-06-16 13:46 UTC, itsmekumari commented on src/e2e-test/resources/cmek-config.properties
> +cmekGCS=projects/cdf-athena/locations/us/keyRings/gcs-cmek-test/cryptoKeys/test_key
Removed.

2022-06-16 13:47 UTC, itsmekumari commented on src/e2e-test/java/io/cdap/plugin/utils/E2ETestConstants.java
> +}
Removed.

2022-06-16 13:47 UTC, itsmekumari commented on src/e2e-test/java/io/cdap/plugin/recordsplitter/actions/RecordSplitterActions.java
> +  private static final Logger logger = LoggerFactory.getLogger(RecordSplitterActions.class);
Removed.

2022-06-16 13:47 UTC, itsmekumari commented on src/e2e-test/features/recordsplitter/BigQueryToRecordSplitter.feature
> +  Scenario: To verify data is getting transferred from BigQuery to BigQuery sink plugin successfully with Delimiter
Changed.

2022-06-16 13:50 UTC, itsmekumari commented
> Add Override service account details steps in all scenarios

Added the Override service account details steps in all scenarios where required.

2022-06-16 15:28 UTC, sawantpritam requested changes

2022-06-16 15:28 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/common/stepsdesign/TestSetupHooks.java
> +  @Before(order = 1, value = "@FILE_SINK_TEST")
Unused

2022-06-17 06:58 UTC, itsmekumari commented on src/e2e-test/java/io/cdap/plugin/common/stepsdesign/TestSetupHooks.java
> +  @Before(order = 1, value = "@FILE_SINK_TEST")
Added a test case with File sink.

2022-06-17 09:05 UTC, sawantpritam commented
> > Add Override service account details steps in all scenarios
> 
> Added the Override service account details steps in all scenarios where required.

Add  below method in TestSetupHook for override to work in macro scenario. 
```
@Before(order = 1)
  public static void overrideServiceAccountFilePathIfProvided()
```
 https://github.com/data-integrations/google-cloud/blob/c3d0fc99448f56a2761d40dee8a2efe84b9ae24a/src/e2e-test/java/io/cdap/plugin/common/stepsdesign/TestSetupHooks.java#L70

2022-06-17 10:22 UTC, itsmekumari commented
> Added the method in TestSetupHook

2022-07-12 09:58 UTC, closed without merging